[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[vars]
N8N_BASIC_AUTH_ACTIVE = "true"
N8N_BASIC_AUTH_USER = "${N8N_BASIC_AUTH_USER}"
N8N_BASIC_AUTH_PASSWORD = "${N8N_BASIC_AUTH_PASSWORD}"
N8N_PORT = "5678"
GENERIC_TIMEZONE = "Africa/Johannesburg"
