[build]
builder = "dockerfile"

[deploy]
startCommand = "n8n"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[vars]
SERVICE_TYPE = "n8n-workflows"
N8N_BASIC_AUTH_ACTIVE = "true"
N8N_BASIC_AUTH_USER = "${N8N_BASIC_AUTH_USER}"
N8N_BASIC_AUTH_PASSWORD = "${N8N_BASIC_AUTH_PASSWORD}"
N8N_HOST = "0.0.0.0"
N8N_PORT = "5678"
N8N_PROTOCOL = "https"
N8N_WEBHOOK_URL = "${RAILWAY_PUBLIC_DOMAIN}"
GENERIC_TIMEZONE = "Africa/Johannesburg"
N8N_DEFAULT_LOCALE = "en"
N8N_USER_MANAGEMENT_DISABLED = "false"
N8N_DISABLE_PRODUCTION_MAIN_PROCESS = "false"
N8N_DISABLE_UI = "false"
N8N_DISABLE_WEBHOOK = "false"
N8N_EXECUTIONS_PROCESS = "main"
N8N_EXECUTIONS_MODE = "regular"
N8N_EXECUTIONS_TIMEOUT = "3600"
N8N_EXECUTIONS_TIMEOUT_MAX = "7200"
N8N_LOG_LEVEL = "info"
N8N_LOG_OUTPUT = "console"

# Database Configuration (Railway PostgreSQL)
N8N_DATABASE_TYPE = "postgresdb"
N8N_DATABASE_POSTGRESDB_HOST = "${DATABASE_HOST}"
N8N_DATABASE_POSTGRESDB_PORT = "${DATABASE_PORT}"
N8N_DATABASE_POSTGRESDB_DATABASE = "${DATABASE_NAME}"
N8N_DATABASE_POSTGRESDB_USER = "${DATABASE_USER}"
N8N_DATABASE_POSTGRESDB_PASSWORD = "${DATABASE_PASSWORD}"
N8N_DATABASE_POSTGRESDB_SCHEMA = "public"

# TenderMatch Integration
TENDERMATCH_API_URL = "${TENDERMATCH_API_URL}"
TENDERMATCH_DB_HOST = "${DATABASE_HOST}"
TENDERMATCH_DB_PORT = "${DATABASE_PORT}"
TENDERMATCH_DB_NAME = "${DATABASE_NAME}"
TENDERMATCH_DB_USER = "${DATABASE_USER}"
TENDERMATCH_DB_PASSWORD = "${DATABASE_PASSWORD}"
